### ISSUE TITLE
Figure out a new name

### ISSUE THREAD

**Issue by TKK13909** [Bali10050/Darkly#40] opened 2024-11-07 22:47 UTC
It's probably time to actually decide on a new name for this project before it gains any more traction. Whether it's Darkly, Brightly, or you just decide to keep the original one. I'm willing to help with the name transition once the decision gets made.

**Comment by Bali10050** [comment] 2024-11-08 16:13
I think Darkly sounds the best, but I'm interested in @DeltaCopy's opinion too, because he has probably spent at least as much time on this project as me, with probably better coding skills than me. Also, if we rename the project we can close #10 pretty quickly. It looks like `./kstyle/lightly.json` changes the name that shows up in the system settings, but I haven't yet found what else needs to be changed to make it work, and I don't know how I can rename everything at once

**Comment by DeltaCopy** [comment] 2024-11-11 16:45
Darkly misconstrued may mean a darker orientated style which it isn't.
Although I am not good with coming up with names, I think that an original name would be better suited.
We already have Lightly, Glassly, Klassly .. For inspiration maybe looking at the style contrast between Breeze and Lightly may help.
The minimalist, clean, and yet still modern looks this application style offers.
breathe, liquid, fluid, zenith, clarity comes to mind.

Whatever is chosen there will be several activities required to reflect the name change

- [ ] refactoring the code
- [ ] updating build instructions
- [ ] validating the application style still works properly, and there are no regressions
- [ ] updating the GitHub Actions CI pipeline which generates the release assets
- [ ] validating the release assets installs still work across the different distributions
- [ ] replacing the AUR and Copr repositories to use the new name as currently both point to "lightly-qt6"

**Comment by TKK13909** [comment] 2024-11-12 21:00
You mentioned 'Clarity' and that gave me an idea. I know some other projects that use Esperanto words for their name (Forgejo is the only one coming to mind at the moment) and the Esperanto word for Clarity is 'Klareco' which incidentally starts with a K like a lot of other stuff in the KDE world.

Just a thought...

By the way, @Bali10050, do you want to use this issue for brainstorming or would you prefer some other method?

**Comment by Bali10050** [comment] 2024-11-13 16:46
> By the way, @Bali10050, do you want to use this issue for brainstorming or would you prefer some other method?

If it works, don't fix it

Also, the name will be decided by the first person who finds out how to properly rename the project, because I have failed miserably in that part.

**Comment by DeltaCopy** [comment] 2024-11-15 20:56
Can you elaborate on what you mean by:

> how to properly rename the project

The repository itself, as well as all the assets inc. the src code cmake build files etc.. ?

**Comment by Bali10050** [comment] 2024-11-15 21:34
> Can you elaborate on what you mean by:
>>    how to properly rename the project

I haven't found out yet what needs to be renamed for it to not only show up in the system settings, but to make it actually selectable, and to make the default lightly installable alongside it.

**Comment by DeltaCopy** [comment] 2024-11-16 12:56
Looking at how Klassy style works will help as it references a lot of Breeze code but still manages to have a different name.
I've just renamed Lightly to Zen as a POC and it works.

Having both Lightly and this new name installed in parallel sounds too difficult to maintain in the long-term.
There are multiple files which require updating including CMakeLists.txt files to reflect the new name.

To give you an idea here are some of them.

      modified:   CMakeLists.txt
      modified:   kstyle/CMakeLists.txt
      modified:   kstyle/config/CMakeLists.txt
      modified:   kstyle/config/lightlystyleconfig.cpp
      modified:   kstyle/config/lightlystyleconfigmodule.cpp
      modified:   kstyle/config/main.cpp    
      modified:   kstyle/lightlystyle.cpp
      modified:   kstyle/lightlystyleconfigdata.kcfgc
      modified:   kstyle/lightlystyleplugin.cpp
      modified:   kstyle/lightlystyleplugin.h
      modified:   liblightlycommon/CMakeLists.txt


![rename](https://github.com/user-attachments/assets/16add248-e40e-41b6-9974-f3bfb663ad6f)

**Comment by Bali10050** [comment] 2024-11-16 22:30
I created a `Rename` branch as a first step

**Comment by huestack** [comment] 2024-12-11 08:46
Boehs has suggested this repo and the other one for Lightly installation, and I think these two repos are going in different directions.

Might I suggest:

**Luxly**:  As a tribute to original author of Lightly. 
**Aeterna**: As in Lux Aeterna (Light Eternal), and again a tribute to original author.

Thanks a lot for picking up this project.

**Comment by DeltaCopy** [comment] 2024-12-21 10:57
A rename makes sense if the plan is to differentiate this project from both boehs and Luwx
The boehs fork now unmaintained did attempt to continue the development originally by Luwx.

The question is whether this fork will continue the work of boehs or go in a completely different direction.

**Comment by Bali10050** [comment] 2024-12-21 12:45
@DeltaCopy can you please help fixing the packages?

**Comment by DeltaCopy** [comment] 2024-12-21 13:04
Are all the changes in the Darkly branch ?

If yes I can make the changes there and test there first.

**Comment by Bali10050** [comment] 2024-12-21 13:11
> Are all the changes in the Darkly branch ?

Yes

Also, thank you for the help

**Comment by Bali10050** [comment] 2024-12-21 13:13
I sent you an invite for collaboration, hopefully that can make your work easier

**Comment by DeltaCopy** [comment] 2024-12-21 13:28
Ok will make the necessary changes in my repo, test and then push.

**Comment by Bali10050** [comment] 2024-12-21 13:32
Thank you!

**Comment by DeltaCopy** [comment] 2024-12-21 19:53
@Bali10050 
There are a lot of changes going into the Darkly branch.
I've renamed all the references to lightly to darkly, in the src code, cmake files as well as all the filenames.
The reason behind this was that all the shared object files being generated still had the lightly name in them.

The packages generated by the GitHub actions are also working.

Comparison.

https://github.com/Bali10050/Darkly/compare/Darkly...DeltaCopy:Darkly

Since this is quite a big refactoring exercise due to the number of changes; let me know if you that is okay to merge.

**Comment by Bali10050** [comment] 2024-12-21 20:29
> let me know if you that is okay to merge

Yes. Also, thank you again for your work!

**Comment by DeltaCopy** [comment] 2024-12-21 20:43
Code merged up into the Darkly branch.

**Comment by DeltaCopy** [comment] 2024-12-21 20:53
This also changes the file of the config file.

From `~/.config/lightlyrc`
To: ~/.config/darklyrc

So any settings which people initially had set will be restored to default, and they will need to set them again.

**Comment by Bali10050** [comment] 2024-12-21 21:18
> So any settings which people initially had set will be restored to default, and they will need to set them again.

I don't think it's a big problem, until you started contributing they had to manually install the dependencies, clone and build every update, I don't think they'll be angry if they need to check a checkmark again as a one-time thing

**Closed** 2024-12-22 00:15 UTC
